修复了Windows下seek不支持float类型的错误
错误现象:
Traceback (most recent call last):
  File "C:\Users\Hrimfaxi\Desktop\shotdown\shotdown\main.py", line 56, in get_su
btitles
    filehash = file_hash.calc_file_hash(filename)
  File "C:\Users\Hrimfaxi\Desktop\shotdown\shotdown\file_hash.py", line 21, in c
alc_file_hash
    r = [ digest_file(f, offset, 4096) for offset in offsets ]
  File "C:\Users\Hrimfaxi\Desktop\shotdown\shotdown\file_hash.py", line 8, in di
gest_file
    f.seek(pos)
OverflowError: Python int too large to convert to C long

Signed-off-by: hrimfaxi <outmatch@gmail.com>